/* 팜인마즈 — 건물 116종 (벽돌깨기 break-it-all 에서 가져옴). cols=폭, fl=층수 범위, roof=지붕, era=시대(0 초가~4 현대), ex=부속물, wall=벽 재질 */
window.BUILDINGS = [
  /* ── 가장 약한 것들부터: 초가집 한 채로 시작한다 ── */
  { ko:'초가집', en:'Straw Hut',     cols:7,  fl:[1,1], roof:'hip',   era:[0,0], ex:[], wall:'wood' },
  { ko:'서당', en:'Village School',       cols:7,  fl:[1,1], roof:'hip',   era:[0,1], ex:[], wall:'wood' },
  { ko:'주막', en:'Tavern',       cols:7,  fl:[1,2], roof:'hip',   era:[0,1], ex:[] },
  { ko:'기와집', en:'Tiled House',     cols:9,  fl:[1,2], roof:'hip',   era:[0,1], ex:[], wall:'wood' },
  { ko:'여인숙', en:'Inn',     cols:7,  fl:[2,2], roof:'gable', era:[0,2], ex:[] },
  { ko:'양조장', en:'Brewery',     cols:8,  fl:[2,3], roof:'gable', era:[0,2], ex:['silo'] },
  { ko:'정미소', en:'Rice Mill',     cols:7,  fl:[2,3], roof:'hip',   era:[0,2], ex:['silo'] },
  { ko:'한의원', en:'Herb Clinic',     cols:7,  fl:[1,2], roof:'hip',   era:[1,3], ex:[] },
  { ko:'비닐하우스', en:'Poly Tunnel', cols:9,  fl:[1,1], roof:'arch',  era:[1,3], ex:[], wall:'glass' },
  /* ── 나무·벽돌 시대: 시골과 마을 ── */
  { ko:'단독주택', en:'House',   cols:7,  fl:[1,3], roof:'gable', era:[0,2], ex:['chimney'] },
  { ko:'연립주택', en:'Townhouse',   cols:8,  fl:[2,3], roof:'twin',  era:[0,2], ex:['chimney'] },
  { ko:'협소주택', en:'Narrow House',   cols:5,  fl:[3,5], roof:'gable', era:[0,3], ex:['chimney'] },
  { ko:'통나무집', en:'Log Cabin',   cols:7,  fl:[1,2], roof:'gable', era:[0,1], ex:['chimney'], wall:'wood' },
  { ko:'농가', en:'Farmhouse',       cols:9,  fl:[1,2], roof:'gable', era:[0,1], ex:['chimney'] },
  { ko:'축사', en:'Barn',       cols:9,  fl:[1,2], roof:'gable', era:[0,1], ex:[], wall:'wood' },
  { ko:'방앗간', en:'Mill',     cols:6,  fl:[2,3], roof:'hip',   era:[0,2], ex:['silo'] },
  { ko:'풍차', en:'Windmill',       cols:5,  fl:[3,4], roof:'hip',   era:[0,2], ex:['blades'] },
  { ko:'교회', en:'Church',       cols:7,  fl:[1,3], roof:'spire', era:[0,2], ex:[] },
  { ko:'한옥', en:'Hanok',       cols:9,  fl:[1,2], roof:'hip',   era:[0,1], ex:[], wall:'wood' },
  { ko:'사찰', en:'Temple',       cols:9,  fl:[1,2], roof:'hip',   era:[0,2], ex:['bell'] },
  { ko:'창고', en:'Warehouse',       cols:9,  fl:[1,2], roof:'arch',  era:[0,3], ex:[] },
  { ko:'여관', en:'Guesthouse',       cols:8,  fl:[2,3], roof:'gable', era:[0,2], ex:['sign'] },
  { ko:'대장간', en:'Forge',     cols:6,  fl:[1,2], roof:'shed',  era:[0,1], ex:['chimney'] },
  { ko:'별장', en:'Cottage',       cols:7,  fl:[1,2], roof:'hip',   era:[0,2], ex:['chimney'] },
  /* ── 벽돌·돌 시대: 읍내와 상권 ── */
  { ko:'학교', en:'School',       cols:9,  fl:[2,3], roof:'flat',  era:[1,3], ex:['clock'] },
  { ko:'상가', en:'Shops',       cols:8,  fl:[1,2], roof:'flat',  era:[1,3], ex:['sign'] },
  { ko:'은행', en:'Bank',       cols:8,  fl:[2,3], roof:'flat',  era:[1,3], ex:['columns'] },
  { ko:'도서관', en:'Library',     cols:9,  fl:[2,3], roof:'dome',  era:[1,3], ex:['columns'] },
  { ko:'우체국', en:'Post Office',     cols:8,  fl:[2,3], roof:'flat',  era:[1,3], ex:['sign'] },
  { ko:'경찰서', en:'Police Station',     cols:8,  fl:[2,3], roof:'flat',  era:[1,3], ex:['tower'] },
  { ko:'시장', en:'Market',       cols:10, fl:[1,2], roof:'shed',  era:[1,3], ex:['sign'] },
  { ko:'빵집', en:'Bakery',       cols:6,  fl:[1,2], roof:'gable', era:[1,3], ex:['sign','chimney'] },
  { ko:'목욕탕', en:'Bathhouse',     cols:8,  fl:[1,2], roof:'flat',  era:[1,3], ex:['stack'] },
  { ko:'공장', en:'Factory',       cols:9,  fl:[1,2], roof:'saw',   era:[1,4], ex:['stack'] },
  { ko:'등대', en:'Lighthouse',       cols:5,  fl:[4,6], roof:'spire', era:[1,4], ex:['lamp'] },
  { ko:'급수탑', en:'Water Tower',     cols:5,  fl:[3,4], roof:'flat',  era:[1,3], ex:['tank'] },
  { ko:'시계탑', en:'Clock Tower',     cols:5,  fl:[4,5], roof:'spire', era:[1,3], ex:['clock'] },
  { ko:'박물관', en:'Museum',     cols:9,  fl:[2,3], roof:'dome',  era:[1,4], ex:['columns'] },
  { ko:'식당', en:'Diner',       cols:7,  fl:[1,2], roof:'flat',  era:[1,3], ex:['sign'] },
  { ko:'카페', en:'Cafe',       cols:6,  fl:[1,2], roof:'gable', era:[1,3], ex:['sign'] },
  { ko:'서점', en:'Bookstore',       cols:7,  fl:[2,2], roof:'flat',  era:[1,3], ex:['sign'] },
  { ko:'약국', en:'Pharmacy',       cols:6,  fl:[1,2], roof:'flat',  era:[1,3], ex:['cross'] },
  { ko:'정비소', en:'Auto Shop',     cols:8,  fl:[1,2], roof:'shed',  era:[1,3], ex:['garage'] },
  { ko:'세탁소', en:'Laundry',     cols:6,  fl:[1,2], roof:'flat',  era:[1,3], ex:['sign','stack'] },
  /* ── 돌·콘크리트 시대: 도시 ── */
  { ko:'시청', en:'City Hall',       cols:9,  fl:[2,3], roof:'dome',  era:[2,4], ex:['clock'] },
  { ko:'법원', en:'Courthouse',       cols:9,  fl:[2,3], roof:'dome',  era:[2,4], ex:['columns'] },
  { ko:'병원', en:'Hospital',       cols:8,  fl:[3,5], roof:'flat',  era:[2,4], ex:['cross'] },
  { ko:'빌라', en:'Low-rise Flats',       cols:8,  fl:[3,4], roof:'flat',  era:[2,4], ex:['balcony','tank'] },
  { ko:'체육관', en:'Gym',     cols:9,  fl:[1,2], roof:'arch',  era:[2,4], ex:['sign'] },
  { ko:'마트', en:'Supermarket',       cols:9,  fl:[1,2], roof:'flat',  era:[2,4], ex:['sign'] },
  { ko:'백화점', en:'Department Store',     cols:9,  fl:[3,4], roof:'flat',  era:[2,4], ex:['sign'] },
  { ko:'기차역', en:'Train Station',     cols:10, fl:[1,2], roof:'arch',  era:[2,4], ex:['clock'] },
  { ko:'버스터미널', en:'Bus Terminal', cols:10, fl:[1,2], roof:'flat',  era:[2,4], ex:['sign'] },
  { ko:'대학교', en:'University',     cols:9,  fl:[2,3], roof:'dome',  era:[2,4], ex:['columns','clock'] },
  { ko:'기숙사', en:'Dormitory',     cols:8,  fl:[3,4], roof:'flat',  era:[2,4], ex:[] },
  { ko:'유치원', en:'Kindergarten',     cols:8,  fl:[1,2], roof:'gable', era:[2,4], ex:['sign'] },
  { ko:'요양원', en:'Care Home',     cols:8,  fl:[2,3], roof:'flat',  era:[2,4], ex:['balcony'] },
  { ko:'온실', en:'Glasshouse',       cols:9,  fl:[1,2], roof:'arch',  era:[2,4], ex:[], wall:'glass' },
  { ko:'격납고', en:'Hangar',     cols:10, fl:[1,2], roof:'arch',  era:[2,4], ex:['garage'] },
  { ko:'발전소', en:'Power Plant',     cols:9,  fl:[1,2], roof:'flat',  era:[2,4], ex:['stack'] },
  { ko:'물류창고', en:'Distribution Center',   cols:10, fl:[1,2], roof:'shed',  era:[2,4], ex:['garage'] },
  { ko:'주유소', en:'Gas Station',     cols:8,  fl:[1,1], roof:'flat',  era:[2,4], ex:['canopy'] },
  { ko:'소방서', en:'Fire Station',     cols:8,  fl:[2,2], roof:'flat',  era:[2,4], ex:['tower','garage'] },
  { ko:'수영장', en:'Swimming Pool',     cols:9,  fl:[1,2], roof:'arch',  era:[2,4], ex:[] },
  { ko:'교도소', en:'Prison',     cols:9,  fl:[2,3], roof:'flat',  era:[2,4], ex:['tower'] },
  /* ── 콘크리트·강철 시대: 현대 도시 ── */
  { ko:'호텔', en:'Hotel',       cols:8,  fl:[4,6], roof:'flat',  era:[3,4], ex:['sign'] },
  { ko:'아파트', en:'Apartment',     cols:8,  fl:[4,6], roof:'flat',  era:[3,4], ex:['tank'] },
  { ko:'오피스텔', en:'Studio Tower',   cols:8,  fl:[4,6], roof:'flat',  era:[3,4], ex:['balcony'] },
  { ko:'오피스', en:'Office',     cols:8,  fl:[4,6], roof:'flat',  era:[3,4], ex:['antenna'] },
  { ko:'펜트하우스', en:'Penthouse', cols:8,  fl:[3,4], roof:'step',  era:[3,4], ex:['balcony'] },
  { ko:'주차타워', en:'Parking Tower',   cols:8,  fl:[4,6], roof:'flat',  era:[3,4], ex:[] },
  { ko:'방송국', en:'Broadcast Center',     cols:7,  fl:[3,4], roof:'flat',  era:[3,4], ex:['antenna'] },
  { ko:'데이터센터', en:'Data Center', cols:9,  fl:[2,3], roof:'flat',  era:[3,4], ex:['tank'] },
  { ko:'연구소', en:'Research Lab',     cols:8,  fl:[3,4], roof:'flat',  era:[3,4], ex:['antenna'] },
  { ko:'컨벤션센터', en:'Convention Center', cols:10, fl:[2,3], roof:'arch',  era:[3,4], ex:['sign'] },
  { ko:'경기장', en:'Stadium',     cols:11, fl:[2,3], roof:'arch',  era:[3,4], ex:['sign'] },
  { ko:'쇼핑몰', en:'Shopping Mall',     cols:10, fl:[2,3], roof:'flat',  era:[3,4], ex:['sign'] },
  { ko:'관제탑', en:'Control Tower',     cols:5,  fl:[5,7], roof:'flat',  era:[3,4], ex:['lamp'] },
  { ko:'전망대', en:'Viewing Tower',     cols:5,  fl:[5,7], roof:'dome',  era:[3,4], ex:['antenna'] },
  { ko:'정유소', en:'Refinery',     cols:9,  fl:[1,2], roof:'flat',  era:[3,4], ex:['stack','silo'] },
  /* ── 골목 상권: 작은 가게들 ── */
  { ko:'편의점', en:'Convenience Store',     cols:6,  fl:[1,2], roof:'flat',  era:[1,4], ex:['sign'] },
  { ko:'꽃집', en:'Flower Shop',       cols:6,  fl:[1,1], roof:'gable', era:[1,4], ex:['sign'] },
  { ko:'정육점', en:'Butcher',     cols:6,  fl:[1,2], roof:'flat',  era:[1,4], ex:['sign'] },
  { ko:'철물점', en:'Hardware Store',     cols:7,  fl:[1,2], roof:'shed',  era:[1,4], ex:['sign'] },
  { ko:'미용실', en:'Hair Salon',     cols:6,  fl:[1,2], roof:'flat',  era:[1,4], ex:['sign'] },
  { ko:'사진관', en:'Photo Studio',     cols:6,  fl:[1,2], roof:'flat',  era:[1,3], ex:['sign'] },
  { ko:'문방구', en:'Stationery Shop',     cols:6,  fl:[1,1], roof:'gable', era:[1,3], ex:['sign'] },
  { ko:'부동산', en:'Realtor',     cols:6,  fl:[1,2], roof:'flat',  era:[2,4], ex:['sign'] },
  { ko:'어시장', en:'Fish Market',     cols:10, fl:[1,1], roof:'shed',  era:[1,3], ex:['sign'] },
  /* ── 관공서·문화 ── */
  { ko:'구청', en:'District Office',       cols:9,  fl:[2,3], roof:'dome',  era:[2,4], ex:['clock'] },
  { ko:'세무서', en:'Tax Office',     cols:9,  fl:[2,3], roof:'flat',  era:[2,4], ex:[] },
  { ko:'대사관', en:'Embassy',     cols:8,  fl:[2,3], roof:'flat',  era:[2,4], ex:['columns'] },
  { ko:'미술관', en:'Art Gallery',     cols:9,  fl:[2,3], roof:'flat',  era:[2,4], ex:['columns'] },
  { ko:'영화관', en:'Cinema',     cols:9,  fl:[2,3], roof:'flat',  era:[2,4], ex:['sign'] },
  { ko:'콘서트홀', en:'Concert Hall',   cols:10, fl:[2,3], roof:'arch',  era:[3,4], ex:['sign'] },
  { ko:'아쿠아리움', en:'Aquarium', cols:10, fl:[2,3], roof:'arch',  era:[3,4], ex:['sign'] },
  { ko:'식물원', en:'Botanical Garden',     cols:9,  fl:[1,2], roof:'arch',  era:[2,4], ex:[], wall:'glass' },
  { ko:'천문대', en:'Observatory',     cols:5,  fl:[4,6], roof:'dome',  era:[2,4], ex:[] },
  /* ── 생활·의료·교육 ── */
  { ko:'학원', en:'Cram School',       cols:8,  fl:[3,4], roof:'flat',  era:[2,4], ex:['sign'] },
  { ko:'독서실', en:'Study Hall',     cols:7,  fl:[2,3], roof:'flat',  era:[2,4], ex:[] },
  { ko:'어린이집', en:'Daycare',   cols:7,  fl:[1,2], roof:'gable', era:[2,4], ex:['sign'] },
  { ko:'치과', en:'Dental Clinic',       cols:7,  fl:[2,3], roof:'flat',  era:[2,4], ex:['cross'] },
  { ko:'동물병원', en:'Vet Clinic',   cols:7,  fl:[1,2], roof:'flat',  era:[2,4], ex:['cross'] },
  { ko:'헬스장', en:'Fitness Center',     cols:8,  fl:[2,3], roof:'flat',  era:[3,4], ex:['sign'] },
  { ko:'볼링장', en:'Bowling Alley',     cols:9,  fl:[1,2], roof:'arch',  era:[3,4], ex:['sign'] },
  { ko:'노래방', en:'Karaoke',     cols:7,  fl:[2,3], roof:'flat',  era:[3,4], ex:['sign'] },
  { ko:'피시방', en:'PC Cafe',     cols:7,  fl:[2,3], roof:'flat',  era:[3,4], ex:['sign'] },
  /* ── 산업 ── */
  { ko:'변전소', en:'Substation',     cols:8,  fl:[1,2], roof:'flat',  era:[2,4], ex:['antenna'] },
  { ko:'정수장', en:'Water Works',     cols:9,  fl:[1,2], roof:'flat',  era:[2,4], ex:['tank'] },
  { ko:'소각장', en:'Incinerator',     cols:9,  fl:[1,2], roof:'flat',  era:[3,4], ex:['stack'] },
  { ko:'제철소', en:'Steel Mill',     cols:10, fl:[1,2], roof:'saw',   era:[3,4], ex:['stack'] },
  { ko:'증권사', en:'Trading House',     cols:8,  fl:[4,5], roof:'flat',  era:[3,4], ex:['antenna'] },
  /* ── 최후: 가장 단단한 것들 ── */
  { ko:'지하벙커', en:'Underground Bunker',   cols:9,  fl:[2,3], roof:'flat',  era:[4,4], ex:['antenna'], wall:'concrete' },
  { ko:'금고', en:'Vault',       cols:7,  fl:[2,3], roof:'flat',  era:[4,4], ex:[], wall:'steel' },
  { ko:'초고층빌딩', en:'Skyscraper', cols:7,  fl:[6,8], roof:'step',  era:[4,4], ex:['antenna'] },
  { ko:'핵방공호', en:'Nuclear Bunker',   cols:9,  fl:[3,4], roof:'flat',  era:[4,4], ex:['antenna','tank'], wall:'steel' },
];
