/* 글로 된 문항 창고. 전부 새로 쓴 문항이다(기존 검사지 문항을 옮기지 않는다).
   각 문항은 [문제, [정답, 오답, 오답, 오답]] — 보기 순서는 tests.js 가 고정 씨앗으로 섞는다. */
window.BANK = {
lang: {
ko: [
  ["의사 : 병원 = 교사 : ?", ["학교", "학생", "칠판", "수업"]],
  ["‘크다’의 반대말은?", ["작다", "넓다", "높다", "길다"]],
  ["맞춤법이 바른 것은?", ["어떻게", "어떡게", "어떻해", "어떻개"]],
  ["손 : 장갑 = 발 : ?", ["양말", "다리", "신발끈", "발가락"]],
  ["낮 : 밤 = 시작 : ?", ["끝", "처음", "중간", "출발"]],
  ["뜻이 비슷한 낱말끼리 묶인 것은?", ["가끔 - 이따금", "자주 - 드물게", "처음 - 마지막", "빨리 - 천천히"]],
  ["‘가랑비에 옷 젖는 줄 모른다’의 뜻은?", ["작은 일도 거듭되면 크게 된다", "비 오는 날엔 우산을 챙겨야 한다", "남의 일에 참견하지 마라", "급할수록 돌아가라"]],
  ["화가 : 그림 = 작곡가 : ?", ["곡", "악기", "가수", "무대"]],
  ["품사가 다른 하나는?", ["예쁘다", "달리다", "먹다", "읽다"]],
  ["‘눈코 뜰 새 없다’의 뜻은?", ["몹시 바쁘다", "몹시 졸리다", "앞이 잘 안 보인다", "매우 놀랐다"]],
  ["빈칸에 알맞은 말은? 그는 늦지 않으려고 (    ) 뛰었다.", ["부리나케", "느릿느릿", "흐지부지", "시름시름"]],
  ["맞춤법이 바른 문장은?", ["금세 다 먹었다", "금새 다 먹었다", "몇일 뒤에 보자", "왠일로 일찍 왔니"]],
  ["‘사공이 많으면 배가 산으로 간다’와 뜻이 가장 가까운 것은?", ["이끄는 사람이 많으면 일이 엉뚱하게 된다", "여럿이 힘을 합치면 일이 쉽다", "배는 산으로 갈 수 없다", "윗사람이 잘해야 아랫사람도 잘한다"]],
  ["쓰임이 틀린 낱말은? 아침 일찍 일어나 운동을 맞추고 학교에 갔다.", ["맞추고", "일찍", "일어나", "갔다"]],
  ["‘가르치다’를 바르게 쓴 문장은?", ["선생님이 수학을 가르치신다", "손가락으로 북쪽을 가르쳤다", "시계가 세 시를 가르킨다", "화살표가 출구를 가르친다"]],
],
en: [
  ["Doctor : Hospital = Teacher : ?", ["School", "Student", "Board", "Lesson"]],
  ["The opposite of ‘big’ is?", ["small", "wide", "tall", "long"]],
  ["Which spelling is correct?", ["definitely", "definately", "definatly", "defanitely"]],
  ["Hand : Glove = Foot : ?", ["Sock", "Leg", "Lace", "Toe"]],
  ["Day : Night = Start : ?", ["End", "Begin", "Middle", "Go"]],
  ["Closest in meaning to ‘rarely’?", ["seldom", "often", "always", "quickly"]],
  ["‘Break the ice’ means?", ["start a conversation", "break something cold", "feel very cold", "end a friendship"]],
  ["Painter : Picture = Composer : ?", ["Song", "Instrument", "Singer", "Stage"]],
  ["Which word is a different part of speech?", ["pretty", "run", "eat", "read"]],
  ["‘Hit the books’ means?", ["study hard", "get angry", "throw books", "buy books"]],
  ["Fill the blank: He ran (    ) to catch the bus.", ["hastily", "sluggishly", "vaguely", "feebly"]],
  ["Which sentence is correct?", ["It’s raining again.", "Its raining again.", "Its’ raining again.", "It raining again."]],
  ["‘Too many cooks spoil the broth’ is closest to?", ["Too many leaders ruin a task", "Many hands make work easy", "Cooking is hard work", "Soup needs more salt"]],
  ["Which word is used wrongly? The affect of the storm was severe.", ["affect", "storm", "was", "severe"]],
  ["Which sentence uses ‘fewer’ correctly?", ["Fewer people came today.", "Fewer water is left.", "Fewer sugar, please.", "Fewer time remains."]],
],
},
nature: {
ko: [
  ["곤충은?", ["개미", "거미", "지네", "달팽이"]],
  ["나머지와 다른 하나는?", ["고래", "상어", "고등어", "참치"]],
  ["식물이 햇빛으로 양분을 만드는 일은?", ["광합성", "증산", "호흡", "발효"]],
  ["겨울잠을 자는 동물은?", ["곰", "사슴", "참새", "토끼"]],
  ["양서류는?", ["개구리", "도마뱀", "거북", "뱀"]],
  ["거미의 다리는 몇 개?", ["8개", "6개", "10개", "4개"]],
  ["나머지와 다른 하나는?", ["박쥐", "펭귄", "독수리", "참새"]],
  ["알을 낳는 포유류는?", ["오리너구리", "캥거루", "박쥐", "돌고래"]],
  ["올챙이가 개구리가 되듯 모습이 크게 바뀌는 것은?", ["탈바꿈", "겨울잠", "광합성", "철 따라 옮겨 다니기"]],
  ["꽃가루를 옮겨 주지 않는 동물은?", ["지렁이", "벌", "나비", "벌새"]],
  ["나머지와 다른 하나는?", ["소나무", "은행나무", "단풍나무", "벚나무"]],
  ["철새가 아닌 것은?", ["참새", "제비", "두루미", "기러기"]],
  ["버섯·곰팡이와 같은 무리(균류)는?", ["표고버섯", "고사리", "이끼", "미역"]],
  ["바다에 사는 포유류가 아닌 것은?", ["바다거북", "물개", "듀공", "범고래"]],
  ["잎에서 물이 수증기가 되어 빠져나가는 일은?", ["증산 작용", "광합성", "발아", "꽃가루받이"]],
],
en: [
  ["Which one is an insect?", ["ant", "spider", "centipede", "snail"]],
  ["Which is the odd one out?", ["whale", "shark", "mackerel", "tuna"]],
  ["Plants making food from sunlight is called?", ["photosynthesis", "transpiration", "respiration", "fermentation"]],
  ["Which animal hibernates?", ["bear", "deer", "sparrow", "rabbit"]],
  ["Which one is an amphibian?", ["frog", "lizard", "turtle", "snake"]],
  ["How many legs does a spider have?", ["8", "6", "10", "4"]],
  ["Which is the odd one out?", ["bat", "penguin", "eagle", "sparrow"]],
  ["Which mammal lays eggs?", ["platypus", "kangaroo", "bat", "dolphin"]],
  ["A tadpole turning into a frog is called?", ["metamorphosis", "hibernation", "photosynthesis", "migration"]],
  ["Which one is NOT a pollinator?", ["earthworm", "bee", "butterfly", "hummingbird"]],
  ["Which is the odd one out?", ["pine", "ginkgo", "maple", "cherry"]],
  ["Which bird does NOT migrate?", ["house sparrow", "swallow", "crane", "wild goose"]],
  ["Which one is a fungus?", ["shiitake", "fern", "moss", "seaweed"]],
  ["Which one is NOT a marine mammal?", ["sea turtle", "seal", "dugong", "orca"]],
  ["Water leaving leaves as vapor is called?", ["transpiration", "photosynthesis", "germination", "pollination"]],
],
},
/* EQ: 얼굴 표정 이름과 상황 판단. sub 'in' = 대인관계, 'me' = 자기성찰 */
emo: {
  ko: { joy: "기쁨", sad: "슬픔", angry: "화남", surprise: "놀람", fear: "두려움", disgust: "역겨움", shy: "부끄러움", bored: "지루함", smug: "비웃음" },
  en: { joy: "joy", sad: "sadness", angry: "anger", surprise: "surprise", fear: "fear", disgust: "disgust", shy: "embarrassment", bored: "boredom", smug: "contempt" },
},
/* 표정 문항: [정답, 오답 셋] */
faces: [
  ["joy", "sad", "angry", "fear"],
  ["sad", "joy", "surprise", "bored"],
  ["angry", "joy", "sad", "shy"],
  ["surprise", "bored", "sad", "angry"],
  ["fear", "surprise", "joy", "bored"],
  ["disgust", "angry", "joy", "surprise"],
  ["shy", "joy", "fear", "smug"],
  ["smug", "joy", "disgust", "shy"],
],
sjt: {
ko: [
  ["in", "친구가 시험을 망쳐 속상하다고 말한다. 가장 좋은 반응은?", ["많이 속상했겠다, 무슨 일이 있었는지 들어 줄게", "다음엔 잘하겠지, 별일 아니야", "나도 망쳤어, 내가 더 심해", "공부를 덜 해서 그런 거 아니야?"]],
  ["me", "중요한 발표 직전에 심장이 빨리 뛰고 손이 떨린다. 가장 좋은 대처는?", ["긴장했다는 걸 받아들이고 숨을 천천히 쉰다", "발표를 다른 사람에게 넘긴다", "아무렇지 않은 척 떨림을 숨기기만 한다", "긴장한 나 자신을 탓한다"]],
  ["in", "모둠 과제에서 한 친구가 맡은 일을 계속 안 한다. 가장 좋은 대처는?", ["따로 만나 사정을 묻고 할 일을 다시 나눈다", "단체 대화방에서 모두가 보게 지적한다", "아무 말 없이 그 몫까지 내가 한다", "선생님께 바로 이름을 알린다"]],
  ["me", "누군가 내 실수를 사람들 앞에서 지적해 화가 치민다. 가장 좋은 대처는?", ["바로 대꾸하지 않고 마음이 가라앉은 뒤 이야기한다", "그 자리에서 상대 실수를 똑같이 지적한다", "꾹 참고 아무에게도 말하지 않는다", "그 사람과 다시는 말하지 않는다"]],
  ["in", "새로 전학 온 친구가 점심시간에 혼자 앉아 있다. 가장 좋은 행동은?", ["같이 먹자고 먼저 말을 건다", "그 친구가 먼저 말을 걸 때까지 기다린다", "다른 친구들과 그 친구 이야기를 한다", "혼자가 편한가 보다 하고 지나친다"]],
  ["me", "열심히 준비한 대회에서 떨어졌다. 가장 좋은 마음가짐은?", ["실망한 마음을 받아들이고 배운 점을 적어 본다", "심사가 불공정했다고 생각한다", "다시는 대회에 나가지 않기로 한다", "아무렇지 않은 척 바로 잊는다"]],
  ["in", "내 말에 친구가 서운해한 것 같다. 가장 좋은 행동은?", ["서운하게 했다면 미안하다고 하고 무엇이 서운했는지 묻는다", "틀린 말은 안 했으니 그냥 둔다", "다른 친구에게 왜 저러는지 묻는다", "기분이 풀릴 때까지 피한다"]],
  ["me", "요즘 까닭 없이 짜증이 자주 난다. 가장 좋은 대처는?", ["언제 짜증이 나는지 살펴보고 까닭을 찾는다", "주변 사람들이 나를 짜증 나게 한다고 생각한다", "군것질을 늘려 기분을 푼다", "원래 성격이 그렇다고 넘긴다"]],
  ["in", "회의에서 내 의견에 누군가 강하게 반대한다. 가장 좋은 대처는?", ["반대하는 까닭을 끝까지 듣고 같은 점을 찾는다", "목소리를 높여 내 의견을 밀어붙인다", "기분이 상해 회의 내내 입을 닫는다", "반대한 사람의 다른 실수를 꺼낸다"]],
  ["me", "하기 싫은 일이 쌓여 계속 미루고 있다. 가장 좋은 대처는?", ["가장 작은 일부터 10분만 해 본다", "마감 직전에 한꺼번에 몰아서 한다", "해야 할 일을 아예 생각하지 않는다", "게으르다며 나 자신을 꾸짖는다"]],
  ["in", "동료가 상사에게 크게 혼나고 자리로 돌아왔다. 가장 좋은 행동은?", ["잠시 뒤 조용히 괜찮은지 묻는다", "무엇을 잘못했는지 바로 캐묻는다", "다른 동료들과 그 일을 이야기한다", "혼날 만했다고 말해 준다"]],
  ["me", "친구의 좋은 소식에 축하보다 부러운 마음이 먼저 든다. 가장 좋은 마음가짐은?", ["부러운 마음을 알아차리고 그래도 진심으로 축하한다", "부러워하는 나는 나쁜 사람이라고 생각한다", "축하하지 않고 모르는 척한다", "친구의 소식을 깎아내린다"]],
],
en: [
  ["in", "A friend says they are upset after failing a test. The best response?", ["That must hurt. Tell me what happened.", "You will do better next time, no big deal.", "I failed too, and mine was worse.", "Maybe you did not study enough?"]],
  ["me", "Right before a big presentation, your heart races and your hands shake. The best move?", ["Accept that you are nervous and breathe slowly.", "Hand the presentation to someone else.", "Just hide the shaking and act fine.", "Blame yourself for being nervous."]],
  ["in", "In a group project, one member keeps skipping their part. The best move?", ["Talk privately, ask why, and split the work again.", "Call them out in the group chat for all to see.", "Quietly do their part yourself.", "Report their name to the teacher right away."]],
  ["me", "Someone points out your mistake in front of others and you feel angry. The best move?", ["Do not reply at once; talk once you have calmed down.", "Point out their mistakes right there.", "Bottle it up and tell no one.", "Never speak to that person again."]],
  ["in", "A new student is sitting alone at lunch. The best action?", ["Invite them to eat together.", "Wait until they talk to you first.", "Talk about them with other friends.", "Assume they like being alone and walk by."]],
  ["me", "You lost a contest you worked hard for. The best mindset?", ["Accept the disappointment and write down what you learned.", "Decide the judging was unfair.", "Decide never to enter a contest again.", "Act fine and forget it at once."]],
  ["in", "A friend seems hurt by something you said. The best action?", ["Say sorry if you hurt them and ask what upset them.", "You said nothing wrong, so leave it.", "Ask another friend what their problem is.", "Avoid them until they get over it."]],
  ["me", "Lately you often feel irritated for no clear reason. The best move?", ["Notice when it happens and look for the cause.", "Decide the people around you are annoying.", "Snack more to feel better.", "Tell yourself that is just who you are."]],
  ["in", "In a meeting, someone strongly opposes your idea. The best move?", ["Hear their reasons fully and look for common ground.", "Raise your voice and push your idea.", "Get upset and stay silent all meeting.", "Bring up their other mistakes."]],
  ["me", "Tasks you dislike are piling up and you keep delaying. The best move?", ["Start the smallest task for just 10 minutes.", "Do everything at the last minute.", "Stop thinking about the tasks at all.", "Scold yourself for being lazy."]],
  ["in", "A coworker comes back after being harshly scolded by the boss. The best action?", ["After a moment, quietly ask if they are okay.", "Ask right away what they did wrong.", "Discuss it with other coworkers.", "Tell them they deserved it."]],
  ["me", "When a friend shares good news, you feel envy before joy. The best mindset?", ["Notice the envy and still congratulate them sincerely.", "Decide you are a bad person for feeling envy.", "Pretend you did not hear and say nothing.", "Play down your friend’s news."]],
],
},
};
/* IQ 낱말 추리(1교시 전용). [단계 0~4, 문제, [정답, 오답...]] — 풀 때마다 단계마다 하나씩 뽑는다 */
BANK.iqv = {
ko: [
  [0, "새 : 둥지 = 벌 : ?", ["벌집", "꿀", "꽃", "날개"]],
  [0, "시작 : 끝 = 출발 : ?", ["도착", "여행", "길", "기차"]],
  [0, "뜻이 가장 넓은 낱말은?", ["악기", "피아노", "바이올린", "기타"]],
  [1, "차갑다 : 얼음 = 뜨겁다 : ?", ["불", "물", "겨울", "바람"]],
  [1, "손 : 손가락 = 나무 : ?", ["가지", "뿌리", "숲", "열매"]],
  [2, "나머지와 다른 하나는?", ["망치", "시계", "자", "온도계"]],
  [2, "나머지와 다른 하나는?", ["숟가락", "컵", "그릇", "접시"]],
  [2, "의사 : 청진기 = 목수 : ?", ["톱", "나무", "집", "의자"]],
  [3, "나머지와 다른 하나는?", ["정육면체", "원", "삼각형", "정사각형"]],
  [3, "책 : 쪽 = 계단 : ?", ["칸", "난간", "층", "엘리베이터"]],
  [4, "관계가 나머지와 다른 것은?", ["소방관 - 불", "의사 - 환자", "교사 - 학생", "변호사 - 의뢰인"]],
  [4, "관계가 나머지와 다른 것은?", ["우유 - 소", "씨앗 - 나무", "애벌레 - 나비", "올챙이 - 개구리"]],
],
en: [
  [0, "Bird : Nest = Bee : ?", ["Hive", "Honey", "Flower", "Wing"]],
  [0, "Start : Finish = Departure : ?", ["Arrival", "Trip", "Road", "Train"]],
  [0, "Which word is the broadest?", ["instrument", "piano", "violin", "guitar"]],
  [1, "Cold : Ice = Hot : ?", ["Fire", "Water", "Winter", "Wind"]],
  [1, "Hand : Finger = Tree : ?", ["Branch", "Root", "Forest", "Fruit"]],
  [2, "Which is the odd one out?", ["hammer", "clock", "ruler", "thermometer"]],
  [2, "Which is the odd one out?", ["spoon", "cup", "bowl", "plate"]],
  [2, "Doctor : Stethoscope = Carpenter : ?", ["Saw", "Wood", "House", "Chair"]],
  [3, "Which is the odd one out?", ["cube", "circle", "triangle", "square"]],
  [3, "Book : Page = Staircase : ?", ["Step", "Railing", "Floor", "Elevator"]],
  [4, "Which pair is different?", ["firefighter - fire", "doctor - patient", "teacher - student", "lawyer - client"]],
  [4, "Which pair is different?", ["milk - cow", "seed - tree", "caterpillar - butterfly", "tadpole - frog"]],
],
};
/* EQ 2판: 글 문항만. [갈래, 문제, [[보기, 점수]...]] 점수 2 = 가장 좋은 답, 1 = 괜찮은 답, 0 = 나쁜 답.
   갈래 read 감정 읽기 · know 감정 이해 · self 자기 감정 관리 · rel 관계 관리.
   보기는 서로 비슷하게, 착하기만 한 답이 늘 정답이 되지 않게 썼다. */
BANK.eq2 = { ko: [
  ["read", "민수는 3년 준비한 시험에 합격했다는 문자를 받고 한참 동안 멍하니 화면만 보고 있다. 지금 민수의 마음에 가장 가까운 것은?", [["얼떨떨함", 2], ["기쁨", 1], ["안도", 1], ["무덤덤함", 0]]],
  ["read", "회의에서 내가 낸 아이디어를 팀장이 자기 생각처럼 발표했다. 동료가 괜찮냐고 묻자 \"응, 상관없어\"라고 짧게 답하고 노트북만 본다. 이 사람의 감정은?", [["억울함", 2], ["서운함", 1], ["무관심", 0], ["피곤함", 0]]],
  ["read", "친구의 결혼 소식에 지은이는 크게 축하했지만, 집에 와서 한참을 혼자 앉아 있었다. 지은이의 마음에 가장 가까운 것은?", [["축하하면서도 쓸쓸한 마음", 2], ["부러움", 1], ["순수한 기쁨", 0], ["화남", 0]]],
  ["read", "발표 전날 밤, 준호는 자료를 세 번째 다시 확인하고도 잠을 이루지 못한다. 준호의 감정은?", [["불안", 2], ["긴장", 1], ["공포", 0], ["짜증", 0]]],
  ["read", "오랜만에 고향에 갔더니 어릴 때 뛰놀던 골목이 모두 헐리고 없었다. 이 사람의 마음에 가장 가까운 것은?", [["허전함과 그리움", 2], ["슬픔", 1], ["분노", 0], ["놀람", 0]]],
  ["read", "동생이 내 옷을 허락 없이 입고 나갔다가 얼룩을 묻혀 왔다. 옷을 내밀며 눈을 못 마주치고 \"미안…\" 한다. 동생의 감정은?", [["죄책감", 2], ["두려움", 1], ["창피함", 1], ["억울함", 0]]],
  ["read", "승진에서 떨어진 동료가 \"오히려 홀가분해\"라며 평소보다 크게 웃는다. 가장 그럴듯한 속마음은?", [["실망을 감추고 있다", 2], ["정말로 홀가분하다", 1], ["기쁘다", 0], ["관심이 없다", 0]]],
  ["read", "새 직장 첫날, 점심시간에 다들 삼삼오오 나가는데 아무도 같이 가자고 하지 않았다. 이때 드는 감정에 가장 가까운 것은?", [["소외감", 2], ["어색함", 1], ["분노", 0], ["죄책감", 0]]],
  ["know", "기대와 불안이 한꺼번에 들 때의 감정에 가장 가까운 것은?", [["설렘", 2], ["조바심", 1], ["후회", 0], ["체념", 0]]],
  ["know", "억울한 일이 풀리지 않은 채 오래 쌓이면 가장 쉽게 바뀌는 감정은?", [["원망", 2], ["체념", 1], ["수치심", 0], ["설렘", 0]]],
  ["know", "아끼던 사람을 떠나보낸 뒤 시간이 흐르며 슬픔이 차츰 바뀌어 가는 감정으로 가장 자연스러운 것은?", [["그리움", 2], ["허탈함", 1], ["분노", 0], ["안도", 0]]],
  ["know", "남을 속여 이득을 본 뒤, 들킬까 봐서가 아니라 스스로 떳떳하지 못해 괴롭다. 이 감정은?", [["죄책감", 2], ["수치심", 1], ["두려움", 0], ["억울함", 0]]],
  ["know", "사람들 앞에서 넘어져 웃음거리가 됐을 때 드는 감정에 가장 가까운 것은?", [["창피함", 2], ["당황", 1], ["죄책감", 0], ["서운함", 0]]],
  ["know", "애인이 다른 사람과 가까워져 나에게서 멀어질까 봐 드는 감정은?", [["질투", 2], ["불안", 1], ["시기", 0], ["부러움", 0]]],
  ["know", "아무리 애써도 상황이 전혀 바뀌지 않는다고 느낄 때 생기기 쉬운 감정은?", [["무력감", 2], ["분노", 1], ["죄책감", 0], ["자부심", 0]]],
  ["know", "친구의 실수로 손해를 봤지만, 친구가 진심으로 사과하고 손해도 메워 주었다. 이때 화가 바뀌기 쉬운 감정은?", [["누그러진 마음", 2], ["고마움", 1], ["원망", 0], ["수치심", 0]]],
  ["self", "중요한 면접에서 떨어져 하루 종일 기분이 가라앉는다. 가장 도움이 되는 행동은?", [["아쉬운 마음을 인정하고, 다음에 바꿀 점 하나를 적어 본다", 2], ["친한 친구에게 털어놓고 위로를 받는다", 1], ["기분 전환으로 밤새 게임을 한다", 0], ["아무 일 없던 것처럼 생각하지 않으려 애쓴다", 0]]],
  ["self", "운전 중 누가 갑자기 끼어들어 화가 확 치민다. 가장 도움이 되는 행동은?", [["숨을 길게 내쉬고, 급한 일이 있나 보다 하고 생각을 바꿔 본다", 2], ["차 안에서 혼자 투덜거리며 털어 버린다", 1], ["경적을 길게 울려 화를 낸다", 0], ["그 차를 따라가며 번호를 기억해 둔다", 0]]],
  ["self", "마감이 몰려 머릿속이 하얘질 만큼 압박감이 든다. 가장 도움이 되는 행동은?", [["할 일을 모두 적고 가장 급한 것 하나부터 시작한다", 2], ["잠깐 산책하며 머리를 식힌다", 1], ["될 대로 되라며 일단 쉰다", 0], ["밤을 새워 한꺼번에 몰아서 끝내려 한다", 0]]],
  ["self", "별것 아닌 일로 가족에게 짜증을 냈고, 나중에 미안해졌다. 가장 좋은 행동은?", [["왜 짜증이 났는지 돌아보고, 가족에게 솔직하게 사과한다", 2], ["맛있는 걸 사 와서 말없이 분위기를 푼다", 1], ["상대도 나를 짜증 나게 했으니 그냥 넘긴다", 0], ["다음부터는 아예 말을 줄이기로 한다", 0]]],
  ["self", "잠들기 전마다 낮에 했던 말실수가 떠올라 괴롭다. 가장 도움이 되는 행동은?", [["정말 문제가 될 일인지 따져 보고, 필요하면 내일 바로잡기로 정한다", 2], ["떠오른 생각을 공책에 적어 둔다", 1], ["다른 생각으로 억지로 덮으려 한다", 0], ["밤에 바로 그 사람에게 연락해 해명한다", 0]]],
  ["self", "좋아하던 일을 해도 몇 주째 즐겁지 않고 무기력하다. 가장 좋은 대처는?", [["믿을 만한 사람에게 이야기하고, 계속되면 전문가 상담을 알아본다", 2], ["작은 일정을 하나씩 정해 몸을 움직여 본다", 1], ["의지가 약해서라며 나를 더 몰아붙인다", 0], ["저절로 나아질 때까지 기다린다", 0]]],
  ["rel", "친구가 연인과 헤어졌다며 전화로 울고 있다. 가장 좋은 첫 반응은?", [["많이 힘들겠다며, 무슨 일이 있었는지 들어 준다", 2], ["더 좋은 사람을 만날 거라고 위로한다", 1], ["헤어진 사람의 나쁜 점을 같이 이야기해 준다", 0], ["기분 전환하자며 당장 밖으로 나오라고 한다", 0]]],
  ["rel", "후배가 같은 실수를 세 번째 반복했다. 다른 사람들도 있는 자리다. 가장 좋은 대처는?", [["따로 불러 실수가 반복되는 까닭을 같이 찾는다", 2], ["그 자리에서 짧고 분명하게 짚어 준다", 1], ["기분 상할까 봐 이번에도 말없이 대신 고친다", 0], ["윗사람에게 알려 처리하게 한다", 0]]],
  ["rel", "친한 친구가 내 부탁을 계속 거절해 서운하다. 가장 좋은 대처는?", [["서운하다고 담담하게 말하고, 친구의 사정도 물어본다", 2], ["마음이 정리될 때까지 시간을 두고 나중에 이야기한다", 1], ["서운한 티를 내지 않고 계속 웃으며 지낸다", 0], ["나도 다음부터 친구 부탁을 거절한다", 0]]],
  ["rel", "내가 진행하는 회의에서 두 동료가 언성을 높이며 다투기 시작했다. 가장 좋은 대처는?", [["잠시 쉬자고 한 뒤, 각자의 요점을 차분히 정리해 다시 말하게 한다", 2], ["분위기가 깨지지 않게 다른 안건으로 넘어간다", 1], ["누가 옳은지 그 자리에서 바로 정해 버린다", 0], ["둘 다 그만하라고 큰 소리로 막는다", 0]]],
  ["rel", "늘 내 일을 도와주던 동료가 정작 자기가 바쁠 땐 도와 달라는 말을 하지 않는다. 가장 좋은 행동은?", [["먼저 구체적으로 내가 도울 일이 있는지 묻는다", 2], ["고마운 마음을 담아 커피를 산다", 1], ["도와 달라고 할 때까지 기다린다", 0], ["그 동료의 일을 몰래 대신 처리해 둔다", 0]]],
  ["rel", "거래처 사람이 몹시 화가 나 전화로 따지는데, 사실 우리 쪽 잘못은 아니다. 가장 좋은 대처는?", [["화가 난 마음을 먼저 인정하고, 끝까지 들은 뒤 사실을 차분히 설명한다", 2], ["우리 잘못이 아니라고 바로 분명히 말한다", 1], ["일단 무조건 사과해서 화를 가라앉힌다", 0], ["화가 가라앉으면 다시 연락하라며 끊는다", 0]]],
],
en: [
  ["read", "Min gets a text saying he passed the exam he prepared for three years. He stares blankly at the screen for a long time. What is he most likely feeling?", [["stunned disbelief", 2], ["joy", 1], ["relief", 1], ["indifference", 0]]],
  ["read", "Your manager presents your idea in a meeting as his own. When a coworker asks if you are okay, you just say \"Yeah, whatever\" and stare at your laptop. What are you feeling?", [["a sense of injustice", 2], ["hurt", 1], ["indifference", 0], ["tiredness", 0]]],
  ["read", "Jane loudly congratulates a friend on her engagement, then sits alone for a long time after getting home. What is closest to her feeling?", [["happy for her, yet lonely", 2], ["envy", 1], ["pure joy", 0], ["anger", 0]]],
  ["read", "The night before his presentation, Joe checks his slides a third time and still cannot sleep. What is he feeling?", [["anxiety", 2], ["tension", 1], ["terror", 0], ["irritation", 0]]],
  ["read", "Visiting your hometown after years, you find the alley you played in as a child has been torn down. What is closest to your feeling?", [["emptiness and nostalgia", 2], ["sadness", 1], ["anger", 0], ["surprise", 0]]],
  ["read", "Your sibling borrowed your shirt without asking and stained it. Handing it back, they avoid your eyes and say \"Sorry…\". What are they feeling?", [["guilt", 2], ["fear", 1], ["embarrassment", 1], ["resentment", 0]]],
  ["read", "A coworker who missed a promotion laughs louder than usual and says \"Honestly, it is a relief.\" What is most likely going on inside?", [["hiding disappointment", 2], ["truly relieved", 1], ["happy", 0], ["does not care", 0]]],
  ["read", "On your first day at a new job, everyone heads out to lunch in groups and nobody invites you. What is closest to your feeling?", [["left out", 2], ["awkward", 1], ["angry", 0], ["guilty", 0]]],
  ["know", "Hope and worry felt at the same time are closest to:", [["excited nervousness", 2], ["impatience", 1], ["regret", 0], ["resignation", 0]]],
  ["know", "When an unfair situation is never resolved and keeps piling up, it most easily turns into:", [["resentment", 2], ["resignation", 1], ["shame", 0], ["excitement", 0]]],
  ["know", "After losing someone dear, sadness most naturally turns over time into:", [["longing", 2], ["emptiness", 1], ["anger", 0], ["relief", 0]]],
  ["know", "After cheating someone for gain, you feel bad not because you might be caught, but because you know it was wrong. This feeling is:", [["guilt", 2], ["shame", 1], ["fear", 0], ["resentment", 0]]],
  ["know", "Tripping and being laughed at in front of people is closest to:", [["embarrassment", 2], ["confusion", 1], ["guilt", 0], ["hurt", 0]]],
  ["know", "Fearing your partner will grow close to someone else and drift away from you is:", [["jealousy", 2], ["anxiety", 1], ["envy", 0], ["admiration", 0]]],
  ["know", "Feeling that nothing changes however hard you try most easily leads to:", [["helplessness", 2], ["anger", 1], ["guilt", 0], ["pride", 0]]],
  ["know", "A friend’s mistake cost you, but they sincerely apologized and made it up to you. Your anger most easily turns into:", [["softening", 2], ["gratitude", 1], ["resentment", 0], ["shame", 0]]],
  ["self", "You failed an important interview and feel down all day. What helps most?", [["Admit the disappointment and write down one thing to change next time.", 2], ["Talk to a close friend and get comfort.", 1], ["Play games all night to forget it.", 0], ["Try hard not to think about it at all.", 0]]],
  ["self", "Someone cuts you off while driving and anger flares up. What helps most?", [["Breathe out slowly and reframe it: maybe they are in a hurry.", 2], ["Grumble to yourself in the car to let it out.", 1], ["Honk long and hard at them.", 0], ["Follow the car and memorize its plate.", 0]]],
  ["self", "Deadlines pile up and the pressure makes your mind go blank. What helps most?", [["List every task and start with the single most urgent one.", 2], ["Take a short walk to clear your head.", 1], ["Give up and rest for now.", 0], ["Stay up all night and do everything at once.", 0]]],
  ["self", "You snapped at family over something small and later feel sorry. What is best?", [["Reflect on why you snapped and apologize honestly.", 2], ["Bring home a treat and smooth things over without words.", 1], ["They annoyed you too, so let it go.", 0], ["Decide to just talk less from now on.", 0]]],
  ["self", "Every night before sleep, a slip of the tongue from the day replays in your head. What helps most?", [["Ask whether it really matters, and if so, decide to fix it tomorrow.", 2], ["Write the thought down in a notebook.", 1], ["Force it away by thinking of something else.", 0], ["Message the person right away at night to explain.", 0]]],
  ["self", "For weeks, even things you used to love feel joyless and you feel drained. What is best?", [["Talk to someone you trust and look into counseling if it continues.", 2], ["Set small daily plans and get moving.", 1], ["Blame weak willpower and push yourself harder.", 0], ["Wait for it to pass on its own.", 0]]],
  ["rel", "A friend calls you crying after a breakup. What is the best first response?", [["Say it must hurt and listen to what happened.", 2], ["Tell them they will meet someone better.", 1], ["Join in listing the ex’s faults.", 0], ["Tell them to come out right now to cheer up.", 0]]],
  ["rel", "A junior coworker repeats the same mistake for the third time, with others around. What is best?", [["Talk privately and work out together why it keeps happening.", 2], ["Point it out briefly and clearly right there.", 1], ["Quietly fix it again so they will not feel bad.", 0], ["Report it to a manager to handle.", 0]]],
  ["rel", "A close friend keeps turning down your requests and you feel hurt. What is best?", [["Calmly say you feel hurt and ask about their situation.", 2], ["Wait until your feelings settle and talk later.", 1], ["Hide it and keep smiling.", 0], ["Start turning down their requests too.", 0]]],
  ["rel", "In a meeting you are leading, two coworkers start raising their voices at each other. What is best?", [["Call a short break, then have each calmly restate their point.", 2], ["Move to another agenda item to keep the peace.", 1], ["Decide on the spot who is right.", 0], ["Shout at both of them to stop.", 0]]],
  ["rel", "A coworker always helps you, yet never asks for help when they are swamped. What is best?", [["Ask them directly what you could take off their plate.", 2], ["Buy them coffee to show thanks.", 1], ["Wait until they ask.", 0], ["Secretly do their work for them.", 0]]],
  ["rel", "An angry client calls to complain, but the problem was not your company’s fault. What is best?", [["Acknowledge their frustration first, hear them out, then calmly explain the facts.", 2], ["Tell them right away that it is not your fault.", 1], ["Apologize unconditionally to calm them down.", 0], ["Ask them to call back when they have calmed down.", 0]]],
],
};
